// <auto-generated />
using System;
using BookingPayments.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingPayments.API.Migrations
{
    [DbContext(typeof(BookPayDbContext))]
    partial class BookPayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookingPayments.API.Entities.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingStatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BookingStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingStatusName = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            BookingStatusName = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            BookingStatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("BookingPayments.API.Entities.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2025, 3, 18, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2770),
                            CheckInDate = new DateTime(2025, 3, 19, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2770),
                            CheckOutDate = new DateTime(2025, 3, 20, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2770),
                            Price = 150,
                            ServiceId = 1,
                            StatusId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2025, 3, 18, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2770),
                            CheckInDate = new DateTime(2025, 3, 21, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2780),
                            CheckOutDate = new DateTime(2025, 3, 22, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2780),
                            Price = 250,
                            ServiceId = 2,
                            StatusId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookingPayments.API.Entities.Discounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountPercentage = 10,
                            IsValid = true,
                            ValidFrom = new DateTime(2025, 3, 18, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2680),
                            ValidTo = new DateTime(2025, 4, 18, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2710)
                        },
                        new
                        {
                            Id = 2,
                            DiscountPercentage = 20,
                            IsValid = true,
                            ValidFrom = new DateTime(2025, 3, 18, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2720),
                            ValidTo = new DateTime(2025, 4, 18, 22, 12, 14, 690, DateTimeKind.Local).AddTicks(2720)
                        });
                });

            modelBuilder.Entity("BookingPayments.API.Entities.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomName = "Room A"
                        },
                        new
                        {
                            Id = 2,
                            RoomName = "Room B"
                        });
                });

            modelBuilder.Entity("BookingPayments.API.Entities.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("longtext");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCancelled = false,
                            Price = 100,
                            ServiceName = "Service A",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCancelled = false,
                            Price = 200,
                            ServiceName = "Service B",
                            TrainerId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
